name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure
        run: git config pull.rebase true && git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"

      - name: Merge master into release
        run: git fetch release && git checkout release && git pull && git merge master

      - name: Remove lib from git ignore
        run: sed 'lib' .gitignore

      - name: Install
        run: yarn
        env:
          NODE_ENV: development

      - name: Build
        run: yarn build:ci
        env:
          NODE_ENV: development

      - name: "Release"
        run: git add -A && git commit -m "release" && git push --follow-tags
